server:
  port: 7000
spring:
  application:
    name: SCW-PAY-CONSUMER
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    alipay-public-key: *******
    app-id: 2016102700771236
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: *****
    notify-url: http://9e9sks.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2
