server:
  port: 5000
spring:
  application:
    name: SCW-PROJECT-CONSUMER
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    end-point: http://oss-cn-beijing.aliyuncs.com
    bucketName: scwdemo
    accessKeyId: LTAI4GCA5zF3nNbvb46ZLPDP
    accessKeySecret: pvYUQcmVuzrgz4yv0ZJJcBjktaq3M1
    bucketDomain: http://scwdemo.oss-cn-beijing.aliyuncs.com