server:
  port: 80
spring:
  application:
    name: SCW-MEMBER-ZUUL
  redis:
    host: localhost
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  #忽略微服务的名称
  ignored-services: "*"
  sensitive-headers: "*"  #在Zuul向其他微服务重定向保持原本的头信息
  routes:   #自定义路由规则
    scw-portal:
      service-id: SCW-AUTH-CONSUMER   #针对SCW-AUTH-CONSUMER 的路由设置
      path: /**   #通过/**访问到SCW-AUTH-CONSUMER 微服务
    scw-project:
      service-id: SCW-PROJECT-CONSUMER
      path: /project/**
    scw-order:
      service-id: SCW-ORDER-CONSUMER
      path: /order/**
    scw-pay:
      service-id: SCW-PAY-CONSUMER
      path: /pay/**
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000

