server:
  port: 7000
spring:
  application:
    name: SCW-PAY-CONSUMER
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuSAYPAEgUMh8eBA4Kz5glDAz7EqF5FSFPVWQ9i7lY8yUgf8V1iQF73LOerdjyISmkjLeBC9Av9GRxIWioT0qjDTJrQ0dGlhE5nbPuSV4YXyckS5xFNJTr07zeSmASr1y0mbT6JvIbDCMpKtf5AJRPlC+6qDbQ0nSgRrnv88tLQQfg/FkubdkCIsfER2s3h+qiC0/GXqYlRxCOljrMqxxPR24XyTOhSxwlRxtxgQqYYTVVmgoy4YQzGAgRSeK4iMqRSRJQYHk3C28XUY5IXXjdFo/QD3UfArgwWW40ZycG2XpWlTdRqWSSvegZjvf/SIBZuKQOC8ggxPXrEYjdmjMQQIDAQAB
    app-id: 2016102700771236
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDD+If7JK+Jf7rkJInKj3miFNbkCl3LZPN0vgRyAzpD9G3p9lAVph224CWOansRJYkIxXe6D8TqnH4+WFzZtjENvfI8B/WcLPf2Szu1U+r2CcOTU9V3Uk2tlO1pDLI5mpocvqcAtlbYlJTeBfBteVxqri17TlbeWpy2v0m56pdFwH8XdhFxHqQ5WuXIOA/BkHWrGL1kEypPJYiChXDj4vOXBlnN7b0gXk0awjm3x3RZ0m0vCLU2qqwTC3Q80Xg0avnXkTWkS6cxf0BYuNyqSsVXud/MI+8rBYo8bQinY9HrLHsGLGqgC0YKA7ts1LVXLCTgWkeRAlqT++EzIUlNhGjtAgMBAAECggEBAKDnhS8N9hsdhyQfZAuvNh2AothmMpD3+HVYN2otgD+fiEfbd/HujONEs1F12EpB2XwcNqvMmtBPYdBq2QHg9/HijewAVQfAXHAbYZEGsBsH9U8YPGNWbnUhnLTuOb/WUsdbOt/41uHJTVnm4nvgc6McFDf0IJs9JwNdmHlQRph7fsDVYVUBICEGRPkptD/7zEY2opggSBRXWqPFpUM59KuhKu+g9RKw+6jgW/DNsrDhsJUmvhnmv+RnH1tee0A0dZ4ATOG+Qc/RmoJNqBR6sC09McVlhBvbkicK9fLFwQIabowVJexJqhQgxbEtATHpQp3gOlSpDeQ8eFLkSrT1w/kCgYEA70S9+U9+z4YWSdp6Qz5ByKDETzq0EXhY3dimP55ufN6nyPAF2TmLH4gJFiDiGXUOHY+n6MIAv3r3AGJ74Sw7Yg3aFonuodwuqZ1zmDTrgxwVgEnh6WzD5b7Ff9uH/yrkQKR9kM58WmLyP+Q3K9S2MBWWLMOoYtvemcdQ+rEQoZ8CgYEA0ayyWx/VVm0wPNHg3UK/gztHqrrvykCF3HWiI7o1DApZ31BaLjv0eozB2dB932y72tKLE8H84GjQc0UmaW7ajI7gDPeea1VRTQUCvxsNbUxL11GBsuse+FCRN5GBPes08CmVkc/it48nNMCKfvZyKrBbpgLlIX5FbfDUdR8qofMCgYEAgU28ALSGSm4jM2w/cIF/mYXQMST/VQWduN4xEeZzvUWylPOppXfkiHjCuFOy/KD2rOEKk83sC47PV0Thv5Fg0h+8QTvvW0ebbAxsANBwih0uPXMwBC7EOy96mhswhqROT+TU+uGr8EjSs9aIPkao4pl3298s66f4x1Agoin4W+8CgYAoCIIxVd2k18orAqOde14Xj1z6oyCfjDxCwI8JpUb1mpBYS/4776SZNYDZtq4h15/ygtqdFh/TNQ//wkc4QDsoNStgLnMn6S1RuFAy7tZcdQHSBbTu1WefX7qqUnTLvrnn1PjC019lTsbckpqe7S0VK4EELG9VOsfE2wOlrSK1swKBgFGdvSJ6KU1TQd1go8WFPL49Gy+TAWAne2mjq+dUlxvsOOW7B1mZnLuFSm3Vr+pVkAUOJRqBbOLwTw6QPKcnpJemQjcdZT6d8MygYet26h/dHOlH+UrKXWpEwL2asrG8LNuBSIix+tqCRQfgtxk9i8Wxj+7CZh+qFh+kiFFNWaAa
    notify-url: http://9e9sks.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2