server:
  port: 4000
spring:
  application:
    name: SCW-AUTH-CONSUMER
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    #redis主机地址
    host: localhost
  session:
    #springSession配置
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    app-code: ****
    host: https://feginesms.market.alicloudapi.com
    path: /codeNotice
    sign: 1
    skin: 1
